### ISSUE TITLE
Top navigation links in header - need to be relative

### ISSUE THREAD

**Issue by mwllr** [web-illinois/illinois_framework_theme#22]
Need to allow the top right links in the header to be relative links so they can be moved between staging and test servers.  This is a setting in the Illinois Framework Theme Header Link List group(https://drupal-sandbox.webtheme.illinois.edu/admin/appearance/settings/illinois_framework_theme)

![Screen Shot 2021-02-19 at 11 28 03 AM](https://user-images.githubusercontent.com/54747669/108539700-f295b580-72a5-11eb-9d48-11c50f04dc52.png)
![Screen Shot 2021-02-19 at 11 28 42 AM](https://user-images.githubusercontent.com/54747669/108539703-f295b580-72a5-11eb-9c85-00efea248704.png)

**Comment by nbaxley-uiuc** [comment]
I think this is a configuration change on the link fields in the header, but probably has to be changed in code.

**Comment by nbaxley-uiuc** [comment]
The configuration I'm talking about is [here](https://drupal-sandbox.webtheme.illinois.edu/admin/appearance/settings/illinois_framework_theme) and I think that the link fields need to be configured so that they allow both internal and external links.  I see that configuration option on [other link fields](https://drupal-sandbox.webtheme.illinois.edu/admin/structure/paragraphs_type/cta/fields/paragraph.cta.field_cta_button) in the UI, but not sure how you configure it in the theme settings.
